### PR TITLE
Vim output formatter

### PR DESCRIPTION
**Pull request by davidosomething**
not sure what you think of this, I'm only modifying for my own use in vim

- FIX - `tern/defs/ecma5` is now `tern/defs/ecmascript`, always enable
- ADD - pick formatter using `--format=vim` or `--format=pretty`

format=vim works with
```
      \   'errorformat':  '%f:%l:%c: %trror: %m,'
      \                 . '%f:%l:%c: %tarning: %m',
```
in neomake

### CODE REVIEW

**Comment by angelozerr** [comment]
Yes it's a good idea. Could you please:

 * update package.json dependencies for tern.
 * add your new feature at https://github.com/angelozerr/tern-lint/wiki/Command-Line

Thanks!

**Comment by davidosomething** [comment]
- updated deps in package.json (including major acorn bump)
- revised some plugin resolving error messaging
- vim output format was updated
    - now outputs like: `index.js:84: error: Invalid argument at 1: cannot convert from string to number` where the `84` is a byte. This needs to be converted into byte2line() via vim. It was necessary because the doc_comment plugin introduces comment lines into the AST but the rest of the linting doesn't run with it so `query.lineNumber` does not include comment lines!


Example config with Neovim's Neomake that successfully parses the new `--format=vim` output:

```
let s:tern_pattern = '\([^:]\+:\)\([^:]\+\)\(.*\)'
let s:tern_replace = '\=submatch(1) . byte2line(submatch(2)) . submatch(3) . " [tern-lint]"'
let s:tern_mapexpr = 'substitute('
      \.   'v:val, '
      \.   "'" . s:tern_pattern . "', "
      \.   "'" . s:tern_replace . "', "
      \.   "''"
      \. ')'
let g:neomake_javascript_ternlint_maker = {
      \   'exe':          'tern-lint',
      \   'args':         [ '--format=vim' ],
      \   'mapexpr':      s:tern_mapexpr,
      \   'errorformat':  '%f:%l: %trror: %m,'
      \                 . '%f:%l: %tarning: %m',
      \ }
```

your original tests still pass, i am using arrow functions from es2015 so node4+ is probably a new requirement for the node engine

**Comment by davidosomething** [comment]
wiki updated for 1.0.0 (bumped version in package.json for this branch/PR)

**Comment by angelozerr** [comment]
Thanks @davidosomething !

**Pull request merged**
