### PR TITLE
Remove unfair comparison with other linters

### PR DESCRIPTION
**Pull request by denis-sokolov**
Checking syntax is simple. Many rules in other linters check for semantic errors.
Things such as empty statements are not syntax errors, but semantic errors.
http://eslint.org/docs/rules/no-empty
Same applies with most of the rules.

With the change the description is a little bit honest while no less great.

### CODE REVIEW

**Comment by angelozerr** [comment]
@denis-sokolov thanks for your comments.

I would like to keep 2 description:

  * type checker like flow
  * semantic is perhaps not the well definition, but I would like to tell that tern-lint is able to validate some features than other linters doesn't do (because it's not their goal), like :
    * validate "string" content like CSS selectors https://github.com/angelozerr/tern-browser-extension#css-selector 
    * unknown module https://github.com/angelozerr/tern-node-extension

**Comment by denis-sokolov** [comment]
Perhaps we should focus on wording like ‘typing’ and ‘advanced linting’. This still sounds positively powerful without being directly misleading about other, less advanced tools.

(PS: tern-browser-extension css selector logic is awesome!)

**Comment by angelozerr** [comment]
> Perhaps we should focus on wording like ‘typing’ 

Not sure, because:

 * tern-lint can be used with [command line](https://github.com/angelozerr/tern-lint/wiki/Command-Line) too.
 * I have integrated ESLint, JSHint with tern to use it with any editor. See https://github.com/angelozerr/tern-jshint and https://github.com/angelozerr/tern-eslint)

>  ‘advanced linting’.

Yes it's better I think. Ihave called that "custom lint". See https://github.com/angelozerr/tern-lint#custom

> (PS: tern-browser-extension css selector logic is awesome!)

Thanks!

**Comment by denis-sokolov** [comment]
I’m sorry, I don’t think I understood your objection on `typing`. What does that have to do with command line or other editors? I meant the concept of type checking that Tern linter provides.

**Comment by denis-sokolov** [comment]
Bump.

**Comment by angelozerr** [comment]
> I’m sorry, I don’t think I understood your objection on typing.

Forget my comment, you are right: typing is the right word.

**Pull request closed without merging**
