### PR TITLE
https://github.com/angelozerr/tern-lint/issues/50

### PR DESCRIPTION
**Pull request by dmitriiKovchin**

### CODE REVIEW

**Comment by dmitriiKovchin** [comment]
I guess one failing test - that was failing even before my commit?

**Comment by angelozerr** [comment]
Thanks @dmitriiKovchin! Could you add a test with your sample with Employee/Customer please

> I guess one failing test - that was failing even before my commit?

Yes it was because tern issue https://github.com/marijnh/tern/issues/610

**Comment by dmitriiKovchin** [comment]
" Could you add a test with your sample with Employee/Customer please"
done

**Comment by angelozerr** [comment]
Thanks @dmitriiKovchin !

**Pull request merged**
